#!/usr/bin/env python3
"""Weekly KPI Review Workflow — Kai reviews, Mara jumps in if anomaly found.

Usage:
    python workflows/weekly_review.py --data path/to/weekly_export.csv
    python workflows/weekly_review.py --data path/to/weekly_export.csv --save "weekly-review-2026-03-18.md"
"""

import argparse
from datetime import date
from pathlib import Path

import anthropic

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents import kai, mara

VAULT_PATH = Path.home() / "Desktop" / "MAIN" / "main_vault"


KAI_WEEKLY_TASK = """Run a Weekly KPI Review (Mode 1). Follow your full process:
1. Compare this week vs. last week (and YoY if data available)
2. Flag any KPI that moved more than ±5% WoW
3. For each significant change, drill into segments to find the driver
4. Flag anything unusual — even positive surprises
5. Connect changes to known events (campaigns, releases, tests, holidays)
6. Use your standard output format: Headlines → Key Movements → Active Tests → Patterns → Recommended Actions

At the end, explicitly flag any movements you CANNOT explain with the available data.
Mark these as: "[NEEDS QUALITATIVE INVESTIGATION]"
"""


MARA_ANOMALY_TASK = """Kai found unexplained anomalies in the weekly KPI review. For each item marked
"[NEEDS QUALITATIVE INVESTIGATION]":

1. **Hypothesize why** — What user behavior could explain this pattern?
2. **Quick research recommendation** — What's the fastest way to get clarity? (session recordings, quick survey, support ticket scan, etc.)
3. **Risk assessment** — Is this urgent or can it wait until next week?

Keep it practical. We need answers, not studies."""


def run_weekly_review(client: anthropic.Anthropic, data: str, model: str = "claude-sonnet-4-6") -> str:
    """Run weekly review: Kai always, Mara only if anomalies found."""

    kai_agent = kai.create_agent(client, model=model)
    mara_agent = mara.create_agent(client, model=model)

    # Step 1: Kai reviews the numbers
    print("📊 Kai is reviewing this week's KPIs...")
    kai_result = kai.run(kai_agent, KAI_WEEKLY_TASK, context=data)

    today = date.today().strftime("%Y-%m-%d")
    output = f"# Weekly CJO Review — {today}\n\n## 📊 Kai — KPI Analysis\n\n{kai_result}"

    # Step 2: Check if Mara is needed
    needs_mara = "[NEEDS QUALITATIVE INVESTIGATION]" in kai_result

    if needs_mara:
        print("🔬 Anomalies found — Mara is investigating...")
        mara_context = f"Weekly data:\n{data}\n\nKai's review:\n{kai_result}"
        mara_result = mara.run(mara_agent, MARA_ANOMALY_TASK, context=mara_context)
        output += f"\n\n---\n\n## 🔬 Mara — Anomaly Investigation\n\n{mara_result}"
    else:
        print("✅ No unexplained anomalies — Mara not needed this week.")
        output += "\n\n---\n\n*No unexplained anomalies — Mara review not triggered.*"

    output += f"\n\n---\n\n*Generated by CJO Team (Kai{' + Mara' if needs_mara else ''})*"

    return output


def main():
    parser = argparse.ArgumentParser(description="CJO Team — Weekly KPI Review")
    parser.add_argument("--data", "-d", required=True, help="Path to weekly data export")
    parser.add_argument("--model", "-m", default="claude-sonnet-4-6", help="Model for agents")
    parser.add_argument("--save", "-s", help="Save to vault with this filename")
    args = parser.parse_args()

    client = anthropic.Anthropic()
    data = Path(args.data).read_text(encoding="utf-8")

    result = run_weekly_review(client, data, model=args.model)
    print(f"\n{result}")

    if args.save:
        output_dir = VAULT_PATH / "Ryzon" / "01_Projects" / "cjo-team-outputs"
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / args.save
        path.write_text(result, encoding="utf-8")
        print(f"\n💾 Saved to: {path}")


if __name__ == "__main__":
    main()
